### PR TITLE
fix: card size and add configuration value to set full size card

### PR DESCRIPTION
**Pull request by idaho**

### CODE REVIEW

**Comment by jankete** [comment]
How is the new sizing option being used?

**Comment by idaho** [comment]
I need to update the readme and editor.
By default it should now have the normal size, like other cards.
If you like to have the card like it was before

Switch to the yaml editor and add at the root level of the card `full_size: true`

**Comment by idaho** [comment]
@jankete i've added the option in PR #107 to the visual editor and updated the readme

**Pull request merged**
